runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3.10.8

manual_scaling:
  instances: 1

env_variables:
  FLASK_APP: main
  FLASK_ENV: development

# Replace YOUR_PROJECT_ID with the ID of your Google Cloud project.
service: idyllic-chimera-377216

# Replace YOUR_PROJECT_ID with the ID of your Google Cloud project.
project_id: MateoHerasClass
